server:
  context-path: /web
  port: 8082
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?generateSimpleParameterMetadata=true&characterEncoding=utf8
    username: root
    password: 123456
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句
#  mvc:
#    view:
#      prefix: /template/
#      suffix: .jsp
#    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix:  
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
workflow:
  url: localhost:8082/workflow